### ISSUE TITLE
Trim Cost wrong?

### ISSUE THREAD

**Issue by Lucky4Luuk** [EndfinityDev/csvExporter#12]
Hey, super grateful for the existence of this exporter plugin. I've been using it to check regulations on cars for this one discord server.

The latest update however seems to have broken Trim Cost. Previously, it seemed to contain the total cost of the car, but now that's no longer the case. My car uses techpool and costs 100.000$ in-game, but the trim cost is only 37k or so. Was Trim Cost always supposed to contain just part of the costs, or did it get broken? Because before, I'm pretty sure it contained the total cost of the car.

**Comment by EndfinityDev** [comment]
CSVExporter only exports already existing Lua data contained within the car, it does not control how things are calculated. Therefore it is not responsible for any changes to stats that happened within the game.

**Comment by Lucky4Luuk** [comment]
That makes sense, thanks! I'll ask around in the automation discord then, because currently the total cost isn't exported anywhere
